const REPO='prop4life/bishops-college-scrabble-fest-2026';
const BRANCH='main';
const API=`https://api.github.com/repos/${REPO}`;
const CFG={u12:{name:'Under 12',folder:'u12',rounds:6},u15:{name:'Under 15',folder:'u15',rounds:6},u20:{name:'Under 20',folder:'u20',rounds:6}};
const $=id=>document.getElementById(id),token=$('token'),event=$('event'),round=$('round'),file=$('file'),msg=$('msg');
token.value=localStorage.getItem('bc_token')||'';for(let i=1;i<=6;i++)round.add(new Option(`Round ${i}`,i));
function say(text,cls=''){msg.className=`panel ${cls}`.trim();msg.textContent=text}
function b64(text){return btoa(unescape(encodeURIComponent(text)))}
function fromB64(s){return decodeURIComponent(escape(atob(String(s||'').replace(/\n/g,''))))}
function cleanId(v){return String(v||'').trim().replace(/^#/,'').replace(/^[A-Z]/i,'')}
function num(v){const t=String(v||'').replace(/\s+/g,'').replace(/−|–|—/g,'-');const m=t.match(/^[+\-]?\d+$/);return m?Number(m[0]):null}
function parsePlayerCell(td){const text=(td?.textContent||'').replace(/\s+/g,' ').trim();const im=text.match(/(?:#|[A-Z])\s*\d+/i);const id=cleanId(im?im[0]:'');let name=text.replace(im?.[0]||'','').trim();const n=td?.querySelector('.name');if(n)name=n.textContent.replace(/\s+/g,' ').trim();return{id,name}}
function parseStandings(html,roundNo){const doc=new DOMParser().parseFromString(html,'text/html');const tables=[...doc.querySelectorAll('table')];const table=tables.find(t=>{const h=[...t.querySelectorAll('tr:first-child th,tr:first-child td')].map(x=>x.textContent.trim().toLowerCase());return h.some(x=>x.includes('player'))&&h.some(x=>x.includes('last game'))})||tables[0];if(!table)return[];const trs=[...table.querySelectorAll('tr')];if(!trs.length)return[];const heads=[...trs[0].querySelectorAll('th,td')].map(x=>x.textContent.trim().toLowerCase());let pi=heads.findIndex(x=>x.includes('player'));if(pi<0)pi=0;let li=heads.findIndex(x=>x.includes('last game'));let si=heads.findIndex(x=>x.includes('spread'));let ri=heads.findIndex(x=>x.includes('rank'));const out=[];for(const tr of trs.slice(1)){const cells=[...tr.children];if(!cells.length)continue;const p=parsePlayerCell(cells[pi]);if(!p.id||!p.name)continue;const last=(li>=0?cells[li]:cells.find(c=>/(?:[WLT])\s*[: ]/.test(c.textContent)))?.textContent.replace(/\s+/g,' ').trim()||'';const m=last.match(/(?:\?\s*)?(?:\d+\s*)?([WLT])\s*[: ]\s*(\d+)\s*[-−–—]\s*(\d+)\s*[: ]\s*(?:#|[A-Z])?\s*(\d+)/i);let cumulative=si>=0?num(cells[si]?.textContent):null;if(cumulative===null){for(const c of cells){const n=num(c.textContent);if(n!==null&&/^[+\-−]?\d+$/.test(c.textContent.trim())){cumulative=n;break}}}if(m)out.push({id:p.id,name:p.name,rank:ri>=0?(parseInt(cells[ri]?.textContent,10)||null):null,round:roundNo,result:m[1].toUpperCase(),score:+m[2],oppScore:+m[3],opponentId:cleanId(m[4]),cumulativeSpread:cumulative})}return out}
async function gh(path,opts={}){opts.headers={...(opts.headers||{}),Authorization:`Bearer ${token.value.trim()}`,Accept:'application/vnd.github+json','Content-Type':'application/json'};const r=await fetch(API+path,opts),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.message||`GitHub error ${r.status}`);return j}
async function put(path,text){const h={Authorization:`Bearer ${token.value.trim()}`,Accept:'application/vnd.github+json'};const old=await fetch(`${API}/contents/${path}?ref=${encodeURIComponent(BRANCH)}`,{headers:h});const body={message:`Publish ${path}`,content:b64(text),branch:BRANCH};if(old.ok)body.sha=(await old.json()).sha;return gh(`/contents/${path}`,{method:'PUT',body:JSON.stringify(body)})}
async function publishedText(path){for(let i=0;i<8;i++){try{const j=await gh(`/contents/${path}?ref=${encodeURIComponent(BRANCH)}`);if(j&&j.content)return fromB64(j.content)}catch(e){}await new Promise(x=>setTimeout(x,500))}return null}
async function rebuild(k){const all=[];for(let r=1;r<=CFG[k].rounds;r++){const n=String(r).padStart(2,'0'),text=await publishedText(`${CFG[k].folder}/round-${n}-standings.html`);if(text)all.push(...parseStandings(text,r))}if(!all.length)throw Error('No recognizable game records were found in the published standings.');all.sort((a,b)=>a.round-b.round);const map={},prev={};for(const x of all){const p=map[x.id]??={id:x.id,name:x.name,rank:null,wins:0,losses:0,ties:0,spread:0,games:[]};p.name=x.name;if(x.rank!==null)p.rank=x.rank;const gs=x.cumulativeSpread===null?null:x.cumulativeSpread-(prev[x.id]??0);if(x.cumulativeSpread!==null)prev[x.id]=x.cumulativeSpread;p.games.push({round:x.round,opponentId:x.opponentId,opponentName:null,result:x.result,score:x.score,oppScore:x.oppScore,spread:gs});if(x.result==='W')p.wins++;else if(x.result==='L')p.losses++;else p.ties++;if(gs!==null)p.spread+=gs}const names=Object.fromEntries(Object.entries(map).map(([id,p])=>[id,p.name]));Object.values(map).forEach(p=>p.games.forEach(g=>g.opponentName=names[g.opponentId]||g.opponentId));return JSON.stringify({event:k,updated:new Date().toISOString(),players:map},null,2)}
async function chooseAndPublish(type){const t=token.value.trim();if(!t)return say('Enter your GitHub access token first.','danger');localStorage.setItem('bc_token',t);file.value='';file.onchange=async()=>{const f=file.files[0];if(!f)return;const k=event.value,r=String(round.value).padStart(2,'0'),ev=CFG[k];try{say('Checking the TSH file…');const text=await f.text();if(type==='standings'&&!parseStandings(text,Number(round.value)).length)throw Error('The uploaded TSH standings contained 0 recognizable game records.');const path=`${ev.folder}/round-${r}-${type}.html`;say(`Publishing ${ev.name} Round ${round.value} ${type}…`);await put(path,text);if(type==='standings'){say('Standings uploaded. Rebuilding player statistics from all published rounds…');await put(`data/${k}.json`,await rebuild(k))}say(`Published successfully.\n${path}${type==='standings'?'\nPlayer statistics rebuilt from all published rounds.':''}`,'success')}catch(e){say(`Publishing failed.\n${e.message}`,'danger')}};file.click()}
$('pairBtn').onclick=()=>chooseAndPublish('pairings');$('standBtn').onclick=()=>chooseAndPublish('standings');
